UnionChain/Controllers/Member/MemberWalletController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using ECFBase.Components;
using ECFBase.Models;
using System.Web.Services;
using ECFBase.Helpers;
using System.IO;
using System.Text.RegularExpressions;

namespace ECFBase.Controllers.Member
{
    public class MemberWalletController : Controller
    {


        #region Utility

        public ActionResult BillHistory(int selectedPage = 1, string SelectedUtilityList = "0", string SelectedStatusList = "ALL")
        {
            try
            {
                if (Session["Username"] == null || Session["Username"].ToString() == "")
                {
                    return RedirectToAction("MemberLogin", "Member", new { reloadPage = true, ExpiredSession = Session["ExpiredSession"].ToString(), FromLoginPage = "No" });
                }


                int pages = 0;
                var model = new UtilitySetupModel();

                DataSet dsBillLog = MemberWalletDB.GetBillByUsername(Session["Username"].ToString(), SelectedUtilityList, SelectedStatusList, selectedPage, out pages);

                selectedPage = ConstructPageList(selectedPage, pages, model);
              

                foreach (DataRow dr in dsBillLog.Tables[0].Rows)
                {
                    var billLog = new UtilityModel();
                    billLog.BillID = Convert.ToInt32(dr["CUTI_BILLID"].ToString());
                    billLog.UtilityDescription = dr["CMULTILANGUTILITY_DESCRIPTION"].ToString();
                    billLog.BillAccount = dr["CUTI_BILLACCOUNT"].ToString();
                    billLog.MobileNumber = dr["CUTI_MOBILENUMBER"].ToString();
                    billLog.ProcessingTime = dr["CUTI_PROCESSTIME"].ToString();
                    billLog.BillAmount = float.Parse(dr["CUTI_BILLAMOUNTRM"].ToString()).ToString("n4");
                    billLog.UNSAmount = float.Parse(dr["CUTI_UNSAMOUNT"].ToString()).ToString("n4");
                    billLog.Fees = float.Parse(dr["CUTI_FEES"].ToString()).ToString("n4");
                    billLog.TotalQP = float.Parse(dr["CUTI_TOTALAMOUNT"].ToString()).ToString("n4");
                    billLog.CreatedDate = Convert.ToDateTime(dr["CUTI_CREATEDON"]).ToString("dd/MM/yyyy hh:mm:ss tt");
                    billLog.Status = Misc.GetUtilityStatus(dr["CUTI_STATUS"].ToString());

                    if (dr["CUTI_STATUS"].ToString() == "0")
                    {
                        billLog.PaymentDate = "";
                    }
                    else
                    {
                        billLog.PaymentDate = Convert.ToDateTime(dr["CUTI_UPDATEDON"]).ToString("dd/MM/yyyy hh:mm:ss tt");
                    }
                    model.BillList.Add(billLog);
                }
                int ok = 0;
                var msg = string.Empty;
                List<UtilitySetupModel> utilities = Misc.GetAllUtilityList(Session["LanguageChosen"].ToString(), Session["CountryCode"].ToString(), ref ok, ref msg);

                model.UtilityList = from c in utilities
                                    select new SelectListItem
                                    {
                                        Text = c.UtilityName,
                                        Value = Convert.ToString(c.UtilityID),
                                    };

                List<UtilitySetupModel> Status = Misc.GetUtilityStatus();

                model.StatusList = from c in Status
                                   select new SelectListItem
                                   {
                                       Text = c.Status,
                                       Value = Convert.ToString(c.Status),
                                   };


               
                return PartialView("UtilityBillHistory", model);
            }
            catch (Exception e)
            {
                Response.Write(e.Message);
                return Json(string.Empty, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult CancelUtilityBill(string ID, string ExpiredSession = "")
        {
            if (Session["Username"] == null || Session["Username"].ToString() == "")
            {
                return RedirectToAction("MemberLogin", "Member", new { reloadPage = true, ExpiredSession = Session["ExpiredSession"].ToString(), FromLoginPage = "No" });
            }

            try
            {

                int ok = 0;
                string msg = "";
                MemberWalletDB.CancelBill(Convert.ToInt32(ID), out ok, out msg);

                if(ok == -1)
                {
                    Response.Write(Resources.Member.WarningUtilityRecordNotFound);
                    return Json(string.Empty, JsonRequestBehavior.AllowGet);
                }

                ViewBag.SessionExpired = ExpiredSession;
                return BillHistory();
            }
            catch (Exception e)
            {
                Response.Write(e.Message);
                return Json(string.Empty, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult UtilityMall(int UtilityID = 0)
        {
            if (Session["Username"] == null || Session["Username"].ToString() == "")
            {
                return RedirectToAction("MemberLogin", "Member", new { reloadPage = true,ExpiredSession = Session["ExpiredSession"].ToString(), FromLoginPage = "No" });
            }

            int ok = 0;
            var msg = string.Empty;
            var csm = new UtilitySetupModel();

            #region UtilityBox
            //combobox for Utility
            List<UtilitySetupModel> utilities = Misc.GetAllUtilityList(Session["LanguageChosen"].ToString(), Session["CountryCode"].ToString(), ref ok, ref msg);

            csm.UtilityList = from c in utilities
                              select new SelectListItem
                              {
                                  Text = c.UtilityName,
                                  Value = Convert.ToString(c.UtilityID),
                              };

            #endregion


            // If admin dint add Ulitiy it cant go in that page, because the dropdown box is empty.
            if (csm.UtilityList.Count() == 0)
            {
                Response.Write("No Utility can bill , please contact admin.");
                return Json(string.Empty, JsonRequestBehavior.AllowGet);
            }

            int totaldays = 0;
            DateTime startdate = DateTime.Now;
            DateTime today = DateTime.Now;
            float CurrentOwn = 0;
            var token = MemberWalletDB.SP_GetHashStatementByUsernameFor300Token(Session["Username"].ToString());
            if(token.Tables[0].Rows.Count!=0)
            {
                startdate = Convert.ToDateTime(token.Tables[0].Rows[0]["CREATEDDATE"].ToString());

                if(startdate != DateTime.Now)
                {
                    TimeSpan difference = today - startdate;
                    totaldays = difference.Days;
                }
           
            }
            if (token.Tables[1].Rows.Count != 0)
            {
                CurrentOwn = float.Parse(token.Tables[1].Rows[0]["WALLETBALANCE"].ToString());
                
            }

            if(totaldays < 30 && CurrentOwn < 300)
            {
                Response.Write(Resources.Member.warningBillPaymentAvailableSuperUser);
                return Json(string.Empty, JsonRequestBehavior.AllowGet);
            }
            else if (totaldays < 30 && CurrentOwn > 300)
            {
                Response.Write(Resources.Member.warningBillPaymentAvailableSuperUser);
                return Json(string.Empty, JsonRequestBehavior.AllowGet);
            }
            else if (totaldays > 30 && CurrentOwn < 300)
            {
                Response.Write(Resources.Member.warningMinUNSAvailable);
                return Json(string.Empty, JsonRequestBehavior.AllowGet);
            }


            DataSet dsBillSetupData = AdminGeneralDB.GetUtilityByID(UtilityID, Session["LanguageChosen"].ToString(), Session["CountryCode"].ToString(), out ok, out msg);
            if (dsBillSetupData.Tables[0].Rows.Count != 0)
            {
                csm.UtilityID = Convert.ToInt32(dsBillSetupData.Tables[0].Rows[0]["CUTI_ID"].ToString());
                csm.UtilityDescription = dsBillSetupData.Tables[0].Rows[0]["CMULTILANGUTILITY_DESCRIPTION"].ToString();
                csm.ProcessingTime = dsBillSetupData.Tables[0].Rows[0]["CUTI_PROCESS"].ToString();
                csm.Mobile = Convert.ToBoolean(dsBillSetupData.Tables[0].Rows[0]["CUTI_MOBILEBILL"].ToString());
                var CurrencyCode = dsBillSetupData.Tables[0].Rows[0]["CCURRENCY_CODE"].ToString();
                csm.MaxAmount = CurrencyCode + dsBillSetupData.Tables[0].Rows[0]["CUTI_MAXAMOUNT"].ToString();
                csm.MinAmount = CurrencyCode + dsBillSetupData.Tables[0].Rows[0]["CUTI_MINAMOUNT"].ToString();
               
                //csm.TotalQP = dsBillSetupData.Tables[0].Rows[0]["CUTI_TOTALQP"].ToString();
                csm.TotalDigit = Convert.ToInt32(dsBillSetupData.Tables[0].Rows[0]["CUTI_DIGIT"].ToString());

                string Code = dsBillSetupData.Tables[0].Rows[0]["CUTI_CODE"].ToString();

                int extensionIndex = dsBillSetupData.Tables[0].Rows[0]["CUTI_IMAGEPATH"].ToString().LastIndexOf('\\');

                string imageName = dsBillSetupData.Tables[0].Rows[0]["CUTI_IMAGEPATH"].ToString().Substring(extensionIndex + 1);
                csm.UtilityImagePath = "http://" + Request.Url.Authority + "/Utility/" + Code + "/" + imageName;
                ViewBag.Currency = "( " + dsBillSetupData.Tables[0].Rows[0]["CCURRENCY_CODE"].ToString() + " )";

            }

            csm.SelectedUtilityList = Convert.ToString(UtilityID);

            DataSet DSTradingInformation = MemberDB.GetTradingInformation();

UnionChain/Views/MemberWallet/TransferOut.cshtml
    <link href="~/Content/resources/nifty-demo.css" rel="stylesheet">
    <script src="~/Content/resources/jquery_005.js"></script>
    <script type="text/javascript" src="~/Content/resources/lang.js"></script>
    <script type="text/javascript" src="~/Content/resources/capital_transfer.js"></script>
    <script src="~/Content/resources/bootbox.js"></script>
    <script src="~/Content/resources/bootstraps.js"></script>
       
                   
   <div id="page-content">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="panel">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">Send out</h3>
                                    </div>
                                    <form action="/user/profile/doOptionSrolledOut" method="post" class="form-horizontal">
                                        <div class="panel-body">
                                            <div class="form-group">
                                                <label class="col-sm-3 control-label">Target wallet address</label>
                                                <div class="col-sm-9">
                                                    <input readonly="true" name="baoress" id="baoress" class="form-control" value="c84e3dad1dae53f7bc8e39b8ee50bee2" type="text">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-sm-3 control-label">Number</label>
                                                <div class="col-sm-9">
                                                    <input name="howmoney" id="howmoney" class="form-control" value="0.0000" readonly="true" type="text">
                                                    <input name="mymoney" id="mymoney" value="0.0000" type="hidden">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-sm-3 control-label">Transaction password</label>
                                                <div class="col-sm-9">
                                                    <input maxlength="20" class="form-control" name="repass" id="repass" onblur="checkrepass()" type="password">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-sm-3 control-label">Captcha</label>
                                                <div class="col-sm-6">
                                                    <input name="captcha" id="captcha" maxlength="50" class="form-control" remote="" placeholder="Verification code" type="text">
                                                </div>
                                                <div class="col-sm-3">
                                                    <img src="~/Content/resources/new.png" onclick="this.src='/captcha/new.html?height=32&amp;width=150&amp;font_size=16&amp;time='+Math.random();" title="换一张" class="captcha captcha-img verify_img" style="cursor: pointer;">
                                                    <input name="_captcha_id" value="" type="hidden">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-sm-3 control-label">Remark information</label>
                                                <div class="col-sm-9">
                                                    <input maxlength="30" name="content" id="content" class="form-control" type="text">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-sm-3 control-label">Explain</label>
                                                <div class="col-sm-9 control-label">
                                                    <span style="color: red">Please check and submit accurately, and cannot be returned after submission.</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="panel-footer text-right">
                                            <input name="opcardbutton" id="opcardbutton" value="Confirm send" class="btn btn-theme btn-success" type="submit">
                                            <input name="type" id="types" value="期权" type="hidden">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
            
           

UnionChain/Views/MemberWallet/WalletOption.cshtml
@{
    ViewBag.Title = "WalletOption";
}

<h2>WalletOption</h2>

UnionChain/Views/MemberWallet/WalletSend.cshtml
@using resMember = ECFBase.Resources.Member;
@using ECFBase.Models
@model TransferWalletModel


<link href="../../Scripts/jquery.ui.dialog.css" rel="stylesheet" type="text/css" />

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<script type="text/javascript">

    $("#OkApproveBtn").click(function (evt) {
        $('#Loading').show();
        Save();
        $("[class *= 'modal-backdrop']").hide();
    });

    function Save() {        
        //$.validator.unobtrusive.parse($('#WalletSend'));
        var token = $('input[name="__RequestVerificationToken"]').val();
            $.ajax({
                type: "POST",
                url: "/MemberWallet/WalletSendMethod",
                data: { __RequestVerificationToken: token, WalletAddress: $(document.getElementById("WalletAddress")).val(), Amount: $('#Amount').val(), PIN: $('#PIN').val(),  Remark: $('#Remark').val()},
                success: function (data) {
                    $("#main-content").html(data);
                    alert("@resMember.msgSaveSuccessfully");
                   $('#Loading').hide();
                },
                error: function (xhr, status, error) {
                    var errorM = xhr.responseText;
                    errorM = errorM.replace('""', '');
                    alert(errorM);
                   $('#Loading').hide();
                }
            });
        //return false;
    };

    $("#btnMobileDeliver").click(function (evt) {
        MobileDeliver();
        $("[class *= 'modal-backdrop']").hide();
    });

    function MobileDeliver() {
        $.ajax({
            type: "POST",
            url: "/MemberWallet/MobileDeliver",
            data: {},
            success: function (data) {
                timer();
            },
            error: function (xhr, status, error) {
                var errorM = xhr.responseText;
                errorM = errorM.replace('""', '');
                alert(errorM);
                $('#Loading').hide();
            }
        });
    };

    $("#btnEmailDeliver").click(function (evt) {
        EmailDeliver();
        $("[class *= 'modal-backdrop']").hide();
    });

    function EmailDeliver() {
        $.ajax({
            type: "POST",
            url: "/MemberWallet/EmailDeliver",
            data: {},
            success: function (data) {
                timer();
            },
            error: function (xhr, status, error) {
                var errorM = xhr.responseText;
                errorM = errorM.replace('""', '');
                alert(errorM);
                $('#Loading').hide();
            }
        });
    };

     var b = $('#getmsalt');
            var text = b.attr('value');
            var counter = b.attr('data-delay');

            //$('#getmsalt').click(function () {
            //    timer();
            //});

            function timer() {
                $('#getmsalt').attr('disabled', 'disabled');
                setTimeout(function () {
                    b.val(text + ' ' + counter);
                    if (counter == 0) {
                        next();
                        $('#getmsalt').removeAttr('disabled');
                        counter = 60;
                    }
                    else {
                        counter--;
                        timer();
                    }
                }, 1000);
            }

            function next() {
                b.val('@resMember.btnGetVerificationCode');
                //whatever happens afterwards
            }


</script>
@{ Html.EnableClientValidation(true); }
@using (Html.BeginForm("WalletSendMethod", "MemberWallet", FormMethod.Post, new { enctype = "multipart/form-data", name = "WalletSend", id = "__RequestVerificationToken" })) //this id very important to do HttpPost
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()
    <div class="modal fade" id="confirmApproveDialog" title="message title" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content" style="text-align: center" align="center">
                <div class="modal-header" style="height: 70px">
                    <button type="button" class="close" data-dismiss="modal">
                        ×
                    </button>
                    <h4>@resMember.lblConfirmation</h4>
                </div>
                <div class="modal-body">
                    <p><b>Confirm To Send</b></p>
                    @*@resAdminHome.WarningRegister*@
                </div>
                <div class="modal-footer">
                    <button type="button" id="OkApproveBtn" class="btn btn-info" data-dismiss="modal"
                            style="width: 100px;" aria-hidden="true">
                        Yes
                    </button>
                    <button type="button" id="CancelConfirmBtn" class="btn btn-info" data-dismiss="modal"
                            style="width: 100px; padding-left: 10px" aria-hidden="true">
                        No
                    </button>
                </div>
            </div>
        </div>
    </div>

    @*<div class="modal fade" id="ReceiveVerificationCodeMethod" role="dialog" aria-hidden="true">
        <div class="modal-dialog" style="width: 450px">
            <div class="modal-content" style="text-align: center" align="center">
                <div class="modal-header" style="height: 70px">
                    <button type="button" class="close" data-dismiss="modal">
                        ×
                    </button>
                    <h4>@resMember.lblReceiveMethod</h4>
                </div>

                <div class="modal-body">
                    <center>
                        <button type="button" id="btnMobileDeliver" class="btn btn-info" data-dismiss="modal" style="width: 49%;" aria-hidden="true">
                            @resMember.lblPhoneMethod
                        </button>
                        <button type="button" id="btnEmailDeliver" class="btn btn-info" data-dismiss="modal" style="width: 49%;" aria-hidden="true">
                            @resMember.lblEmailMethod
                        </button>
                    </center>
                </div>
            </div>
        </div>
    </div>*@


    <div id="main-content">
        <div class="row">
            <div class="col-lg-2 col-md-offset-0  col-sm-offset-0"></div>
            <div class="col-lg-8 col-md-12">
                <div class="panel">
                    <div class="panel-heading">
                        <h3 class="panel-title">@resMember.mnuWalletSend</h3>
                    </div>
                    <form class="form-horizontal">
                        <div class="panel-body">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">@resMember.lblUNSQuantity</label>
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(model => model.Wallet, new { @class = "form-control", @disabled = "disabled" })
                                </div>
                            </div>
                            <br />
                            <div class="form-group">
                                <label class="col-sm-3 control-label">@resMember.lblSendWalletAddress</label>
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(model => model.WalletAddress, new { @class = "form-control", @ID = "WalletAddress" })
                                </div>
                            </div>
                            <br />
                            <div class="form-group">
                                <label class="col-sm-3 control-label">@resMember.lblSendOutQty</label>
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(model => model.Amount, new { @class = "form-control", @ID = "Amount" })
                                </div>
                            </div>

                            @*<div class="form-group">
            <label class="col-sm-3 control-label">&nbsp;</label>
            <div class="col-sm-6">
                @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control", @disabled = "disabled" })
            </div>
            <div class="col-sm-3">
                <input class="btn btn-success"  data-toggle="modal" data-target="#ReceiveVerificationCodeMethod" style="font-size:small" type="button" value="@resMember.btnGetVerificationCode" id="getmsalt" data-delay="120"> </input>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">code</label>
            <div class="col-sm-9">
                @Html.TextBoxFor(model => model.VerificationCode, new { @class = "form-control", @ID = "VerificationCode" })
            </div>
        </div>*@
                            <br />
                            <div class="form-group">
                                <label class="col-sm-3 control-label">@resMember.lblRemark</label>
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(model => model.Remark, new { @class = "form-control", @ID = "Remark" })
                                </div>
                            </div>
                            <br />
                            <div class="form-group">
                                <label class="col-sm-3 control-label">@resMember.lblTransactionPassword</label>
                                <div class="col-sm-9">
                                    @Html.PasswordFor(model => model.PIN, new { @class = "form-control", @ID = "PIN" })
                                </div>
                            </div>
                            <br />
                            <div class="form-group">
                                <label class="col-sm-3 control-label">@resMember.lblReminder3</label>
                                <div class="col-sm-9 control-label">
                                    <span style="color: #FFF">@resMember.lblReminder2</span>
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer text-right">
                            <span style="color: #FFF">@resMember.WarningPerformRealnameCertification</span>&nbsp;&nbsp;&nbsp;
                            @if (Model.CanTransfer != "1")
                            {
                                <button id="btnSave" type="button" class="btn btn-lm btn-theme" style="width: 150px" data-toggle="modal" data-target="#confirmApproveDialog">@resMember.btnConfirmSend</button>
                            }
                            else
                            {
                                <button id="btnSave" type="button" disabled class="btn btn-lm btn-theme" style="width: 150px" data-toggle="modal" data-target="#confirmApproveDialog">@resMember.btnConfirmSend</button>
                            }


                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-2 col-md-offset-0 col-sm-offset-0"></div>
        </div>
    </div>
}