UnionChain/Controllers/Admin/AdminShareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ECFBase.Models;
using ECFBase.Components;
using System.Data;
using System.Globalization;
using System.IO;
using System.Web.UI;
using System.Text;

namespace ECFBase.Controllers.Admin
{
    public class AdminShareController : Controller
    {

        public ActionResult TradingPriceAdjustment()
        {
            try
            {
                if (Session["Admin"] == null || Session["Admin"].ToString() == "")
                {
                    return RedirectToAction("AdminLogin", "Admin", new { reloadPage = true });
                }

                int Page = 0;
                int ok = 0;
                string msg = string.Empty;

                ShareLogModel model = new ShareLogModel();

                DataSet dsTradingPrice = MemberShareDB.GetTradingPriceValue();
                if(dsTradingPrice.Tables[0].Rows.Count != 0 )
                {
                    model.TradingAdjustmentID = dsTradingPrice.Tables[0].Rows[0]["CPI_ID"].ToString();
                    model.Value = dsTradingPrice.Tables[0].Rows[0]["CPI_VALUE"].ToString();
                }


                return PartialView("TradingPriceAdjustment", model);
            }
            catch (Exception e)
            {
                Response.Write(e.Message);
                return Json(string.Empty, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult TradingSavePrice(string Price = "0", int ID = 0)
        {
            try
            {
                if (Session["Admin"] == null || Session["Admin"].ToString() == "")
                {
                    return RedirectToAction("AdminLogin", "Admin", new { reloadPage = true });
                }

                int ok = 0;
                string msg = string.Empty;

                if(Price == "0")
                {
                    Response.Write(Resources.Member.warningPlsInputTradingPrice);
                    return Json(string.Empty, JsonRequestBehavior.AllowGet);
                }
               
                MemberShareDB.SaveTradingPriceValue(Price, ID, Session["Admin"].ToString(), out ok, out msg);

                return TradingPriceAdjustment();
            }
            catch (Exception e)
            {
                Response.Write(e.Message);
                return Json(string.Empty, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult TradingBuyingQueue(int SelectedPage = 1, string Username = "" , string Status = "" , string Rate = "" , string StartTime = "" , string EndTime = "" )
        {
            try
            {
                if (Session["Admin"] == null || Session["Admin"].ToString() == "")
                {
                    return RedirectToAction("AdminLogin", "Admin", new { reloadPage = true });
                }

                int Page = 0;
                int ok = 0;
                string msg = string.Empty;

                ShareLogModel model = new ShareLogModel();

                DataSet dsTradingBuyingQueue = MemberShareDB.GetAllTradingBuyingQueue(Username , Status , Rate , StartTime , EndTime ,Convert.ToInt32(SelectedPage), out Page , out ok , out msg );

                SelectedPage = ConstructPageList(SelectedPage, Page, model);

                foreach (DataRow dr in dsTradingBuyingQueue.Tables[0].Rows)
                {
                    ShareListLogModel TradingBuy = new ShareListLogModel();
                        TradingBuy.Username = dr["CUSR_USERNAME"].ToString();
                        TradingBuy.OriValue = dr["CTBQ_ORI_VALUE"].ToString();
                        TradingBuy.PendingValue = dr["CTBQ_VALUE"].ToString();
                        TradingBuy.Status = Misc.TradingStatus(dr["CTBQ_STATUS"].ToString());
                        TradingBuy.Rate = dr["CTBQ_RATE"].ToString();
                        TradingBuy.Amount = dr["CTBQ_AMOUNT"].ToString();
                        TradingBuy.LocalAmount = dr["CTBQ_LOCAL_AMOUNT"].ToString();
                        TradingBuy.Date = Convert.ToDateTime(dr["CTBQ_CREATEDON"]).ToString("dd-MM-yyyy hh:mm:ss tt");
                    
                    model.TradingBuyQueue.Add(TradingBuy);
                }

                List<Status> StatusList = Misc.DBGetAllBuyQueueStatusList("BUY");

                model.StatusList = from c in StatusList
                                         select new SelectListItem
                                         {
                                             Text = c.StatusDisplay,
                                             Value = c.StatusX
                                         };


                model.MemberID = Username;
                model.TheRate = Rate;
                model.SelectedStatus = Status;
                return PartialView("TradingBuyingQueue", model);
            }
            catch (Exception e)
            {
                Response.Write(e.Message);
                return Json(string.Empty, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult TradingSellingQueue(int SelectedPage = 1, string Username = "", string Status = "", string Rate = "", string StartTime = "", string EndTime = "")
        {
            try
            {
                if (Session["Admin"] == null || Session["Admin"].ToString() == "")
                {
                    return RedirectToAction("AdminLogin", "Admin", new { reloadPage = true });
                }

                int Page = 0;
                int ok = 0;
                string msg = string.Empty;

                ShareLogModel model = new ShareLogModel();

                DataSet dsTradingSellingQueue = MemberShareDB.GetAllTradingSellingQueue(Username, Status, Rate, StartTime, EndTime, Convert.ToInt32(SelectedPage), out Page, out ok, out msg);

                SelectedPage = ConstructPageList(SelectedPage, Page, model);

                foreach (DataRow dr in dsTradingSellingQueue.Tables[0].Rows)
                {
                    ShareListLogModel TradingSell = new ShareListLogModel();

                    TradingSell.Username = dr["CUSR_USERNAME"].ToString();
                    TradingSell.OriValue = dr["CTSQ_ORI_VALUE"].ToString();
                    TradingSell.PendingValue = dr["CTSQ_VALUE"].ToString();
                    TradingSell.Status = Misc.TradingStatus(dr["CTSQ_STATUS"].ToString());
                    TradingSell.Rate = dr["CTSQ_RATE"].ToString();
                    TradingSell.Amount = dr["CTSQ_AMOUNT"].ToString();
                    TradingSell.LocalAmount = dr["CTSQ_LOCAL_AMOUNT"].ToString();
                    TradingSell.Date = Convert.ToDateTime(dr["CTSQ_CREATEDON"]).ToString("dd-MM-yyyy hh:mm:ss tt");

                    model.TradingSellQueue.Add(TradingSell);
                }

                List<Status> StatusList = Misc.DBGetAllBuyQueueStatusList("SELL");

                model.StatusList = from c in StatusList
                                   select new SelectListItem
                                   {
                                       Text = c.StatusDisplay,
                                       Value = c.StatusX
                                   };

             
                model.MemberID = Username;
                model.TheRate = Rate;
                model.SelectedStatus = Status;

                return PartialView("TradingSellingQueue", model);
            }
            catch (Exception e)
            {
                Response.Write(e.Message);
                return Json(string.Empty, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult TradingMatchQueue(int SelectedPage = 1, string Buyer = "" , string Seller = "", string Status = "", string Rate = "", string StartTime = "", string EndTime = "")
        {
            try
            {
                if (Session["Admin"] == null || Session["Admin"].ToString() == "")
                {
                    return RedirectToAction("AdminLogin", "Admin", new { reloadPage = true });
                }

                int Page = 0;
                int ok = 0;
                string msg = string.Empty;

                ShareLogModel model = new ShareLogModel();

                DataSet dsTradingSellingQueue = MemberShareDB.GetAllTradingMatchQueue(Buyer, Seller, Status, Rate, StartTime, EndTime, Convert.ToInt32(SelectedPage), out Page, out ok, out msg);

                SelectedPage = ConstructPageList(SelectedPage, Page, model);

                foreach (DataRow dr in dsTradingSellingQueue.Tables[0].Rows)
                {
                    ShareListLogModel TradingSell = new ShareListLogModel();

                    TradingSell.Buyer = dr["CTMP_BUYER"].ToString();
                    TradingSell.Seller = dr["CTMP_SELLER"].ToString();
                    TradingSell.OriValue = dr["CTMP_SELLER_VALUE"].ToString();
                    TradingSell.Status = Misc.TradingStatus(dr["CTMP_STATUS"].ToString());
                    TradingSell.Amount = dr["CTMP_SELLER_AMOUNT"].ToString();
                    TradingSell.LocalAmount = dr["CTMP_SELLER_LOCAL_AMOUNT"].ToString();
                    TradingSell.Date = Convert.ToDateTime(dr["CTMP_CREATEDON"]).ToString("dd-MM-yyyy hh:mm:ss tt");

                    model.TradingSellQueue.Add(TradingSell);
                }

                List<Status> StatusList = Misc.DBGetAllBuyQueueStatusList("SELL");

                model.StatusList = from c in StatusList
                                   select new SelectListItem
                                   {
                                       Text = c.StatusDisplay,
                                       Value = c.StatusX
                                   };

                model.Buyer = Buyer;
                model.Seller = Seller;
                model.TheRate = Rate;
                model.SelectedStatus = Status;
   

UnionChain/Views/AdminShare/TradingBuyingQueue.cshtml
@using ECFBase.Models
@model ShareLogModel
@using resShared  = ECFBase.Resources.Member;
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<link rel="stylesheet" href="/resources/demos/style.css">

<script type="text/javascript">
    
    $("#btnExport").click(function (evt) {
        $('#Loading').show();

        var e = document.getElementById("page")
        var page = e.options[e.selectedIndex].value;
        $.ajax({
            type: "POST",
            url: "/AdminShare/ExportBuyingQueue",
            data: {
                selectedPage: page, Username: $(document.getElementById("Username")).val(), Rate: $(document.getElementById("TheRate")).val(), Status: $(document.getElementById("Status")).val(), StartTime: $(document.getElementById("startdate")).val(), EndTime: $(document.getElementById("enddate")).val()
            },
            success: function (data) {
                $("#main-content").html(data);
                $('#Loading').hide();
            },
            error: function (xhr, status, error) {
                var errorM = xhr.responseText;
                errorM = errorM.replace('""', '');
                alert(errorM);
                $('#Loading').hide();
            }
        });
    });       

    $("#btnPage").click(function (evt) {
        $('#Loading').show();

        var e = document.getElementById("page")
        var page = e.options[e.selectedIndex].value;
        $.ajax({
            type: "POST",
            url: "/AdminShare/TradingBuyingQueue",
            data: {
                selectedPage: page, Username: $(document.getElementById("Username")).val(), Rate: $(document.getElementById("TheRate")).val(), Status: $(document.getElementById("Status")).val(), StartTime: $(document.getElementById("startdate")).val(), EndTime: $(document.getElementById("enddate")).val()
            },
            success: function (data) {
                $("#main-content").html(data);
               $('#Loading').hide();
            },
            error: function (xhr, status, error) {
                var errorM = xhr.responseText;
                errorM = errorM.replace('""', '');
                alert(errorM);
               $('#Loading').hide();
            }
        });
        });       

    $("#btnsearch").click(function (evt) {
            $('#Loading').show();
            var e = document.getElementById("page");
            var page = e.options[e.selectedIndex].value;
            $.ajax({
                type: "POST",
                url: "/AdminShare/TradingBuyingQueue",
                data: {                    
                    selectedPage: page, Username: $(document.getElementById("Username")).val(), Rate: $(document.getElementById("TheRate")).val(), Status: $(document.getElementById("Status")).val(), StartTime: $(document.getElementById("startdate")).val(), EndTime: $(document.getElementById("enddate")).val()
                },
                success: function (data) {
                    $("#main-content").html(data);
                    $('#Loading').hide();
                },
                error: function (xhr, status, error) {
                    var errorM = xhr.responseText;
                    errorM = errorM.replace('""', '');
                    alert(errorM);
                    $('#Loading').hide();
                }
            });
        });
  
    $(function () {

            $("#startDate").datepicker({
                altField: "#alternate",
                altFormat: "DD, d MM, yy",
            format: 'dd-mm-yyyy'
            });
        });      

    $(function () {

            $("#endDate").datepicker({
                altField: "#alternate",
                altFormat: "DD, d MM, yy",
            format: 'dd-mm-yyyy'
            });
        });      

    </script>

<div>

    <div class="row">
        <div class="col-lg-12">
            <h2 style="padding-left:15px;">Trading</h2>
            <!-- Begin breadcrumb -->
            <ol class="breadcrumb default square rsaquo sm no-border " style="margin:15px;">
                <li><a href="javascript:;" id="Home"><i class="fa fa-home"></i></a></li>
                <li><a href="#">Trading</a></li>
                <li class="active"><a href="#" onclick="dummy(0);return false;"> Trading Buying Queue </a></li>
            </ol>
            <!-- Begin breadcrumb -->
            <h1 class="page-sub-header"></h1>
        </div>
    </div>

        
    <div class="table-responsive">
        <table width="100%" class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <tr>
                <td style="text-align:right">
                    <label>@resShared.lblUsername:</label>
                </td>
                <td style="padding-left:10px; width:200px">
                    @Html.TextBoxFor(m => m.MemberID, Model.MemberID, new { @id = "Username", @class = "form-control", style = "width:200px;" })
                </td>
            </tr>
            <tr>
                <td style="text-align:right">
                    <label>@resShared.lblStatus:</label>
                </td>
                <td style="padding-left:10px; width:200px">
                    @Html.DropDownListFor(m => m.SelectedStatus, Model.StatusList, new { @id = "Status", @class = "form-control", style = "width:200px;" })
                </td>
                <td style="padding-left:10px"></td>
            </tr>
            <tr>
                <td style="text-align:right">
                    <label>@resShared.lblPrice:</label>
                </td>
                <td style="padding-left:10px; width:200px">
                    @Html.TextBoxFor(m => m.TheRate, Model.TheRate, new { @id = "TheRate", @class = "form-control", style = "width:200px;" })
                </td>
                <td style="padding-left:10px"></td>
            </tr>
            <tr>
                <td style="text-align:right">
                    <label>@resShared.lblDateFrom:</label>
                </td>
                <td style="padding-left:10px; width:200px">
                    <input type="text" id="startDate">
                </td>

            </tr>
            <tr>
                <td style="text-align:right">
                    <label> @resShared.lblTo:</label>
                </td>
                <td style="padding-left:10px; width:200px">
                    <input type="text" id="endDate">
                </td>
                <td style="padding-left:10px">
                    <button id="btnsearch" type="button" class="btn btn-sm btn-success" style="width:100px">@resShared.btnSearch</button>
                </td>
            </tr>
            <tr></tr>
            <tr>
                <td style="text-align:right">
                   
                </td>
                <td style="padding:10px 10px;">
                    <a href="@Url.Action("ExportBuyingQueue", "AdminShare", new {Username = @Model.MemberID, Status = @Model.SelectedStatus, startdate = @Model.startDate, enddate = @Model.endDate })" class="btn btn-sm btn-primary" target="_blank" style="width:100px">@resShared.btnExport</a>
                </td>
                <td style="padding-left:10px">
                    @*<button id="btnExport" type="button" class="btn btn-sm btn-primary" style="width:100px">@resShared.btnExport</button>*@
                  
                </td>
            </tr>
        </table>
    </div>
    <div class="table-responsive">
        <table id="tablestyle" border="1" class="table-style table table-th-block table-hover">
            <thead>
                <tr>
                    <th style="text-align: center;color:White">
                        @resShared.lblUsername
                    </th>
                    <th style="text-align: center;color:White">
                        @resShared.lblVolume
                    </th>
                    <th style="text-align: center;color:White">
                        @resShared.lblPendingVolume
                    </th>
                    <th style="text-align: center;color:White">
                        @resShared.lblPrice
                    </th>
                    <th style="text-align: center;color:White">
                        @resShared.lblStatus
                    </th>
                    <th style="text-align: center;color:White">
                        lblDate
                    </th>
                </tr>
            </thead>
            <tbody style="background-color: #eee;">
                @if (Model.TradingBuyQueue.Count == 0)
                {
                    <tr style="height: 25px; border-top: 2px solid white;">
                        <td style="padding: 5px;" colspan="10">
                            @resShared.lblNoRecFound
                        </td>
                    </tr>
                }
                @if (Model.TradingBuyQueue != null)
                {
                    foreach (var item in Model.TradingBuyQueue)
                    {
                        string style = "";

                        <tr style=@style>

                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Username)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.OriValue)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.PendingValue)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Rate)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Status)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Date)
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    @if (Model.TradingBuyQueue.Count > 0)
    {
        <table width="auto" style="text-align:right; margin-right:0px; margin-left:auto;">
            <tr>
                <td style="text-align: right">
                    <div class="BtnClass" style="float: right;">
                        @Html.DropDownList("page", @Model.Pages, new { @class = "form-control", style = "width:80px;" })

                    </div>
                </td>
                <td style="text-align: right">
                    <button id="btnPage" type="button" class="btn btn-sm btn-success" style="width: 100px">@resShared.btnView</button>
                </td>
            </tr>
        </table>
    }
    <br />
    <br />
    <br />

</div>

UnionChain/Views/AdminShare/TradingMatchQueue.cshtml
@using ECFBase.Models
@model ShareLogModel
@using resShared  = ECFBase.Resources.Member;
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<link rel="stylesheet" href="/resources/demos/style.css">

<script type="text/javascript">

    $("#btnPage").click(function (evt) {
        $('#Loading').show();

        var e = document.getElementById("page")
        var page = e.options[e.selectedIndex].value;
        $.ajax({
            type: "POST",
            url: "/AdminShare/TradingMatchQueue",
            data: {
                selectedPage: page, Buyer: $(document.getElementById("Buyer")).val(),Seller: $(document.getElementById("Seller")).val(), Rate: $(document.getElementById("TheRate")).val(), Status: $(document.getElementById("Status")).val(), StartTime: $(document.getElementById("startdate")).val(), EndTime: $(document.getElementById("enddate")).val()
            },
            success: function (data) {
                $("#main-content").html(data);
               $('#Loading').hide();
            },
            error: function (xhr, status, error) {
                var errorM = xhr.responseText;
                errorM = errorM.replace('""', '');
                alert(errorM);
               $('#Loading').hide();
            }
        });
        });       

    $("#btnsearch").click(function (evt) {
            $('#Loading').show();
            var e = document.getElementById("page");
            var page = e.options[e.selectedIndex].value;
            $.ajax({
                type: "POST",
                url: "/AdminShare/TradingMatchQueue",
                data: {                    
                    selectedPage: page, Buyer: $(document.getElementById("Buyer")).val(),Seller: $(document.getElementById("Seller")).val(), Rate: $(document.getElementById("TheRate")).val(), Status: $(document.getElementById("Status")).val(), StartTime: $(document.getElementById("startdate")).val(), EndTime: $(document.getElementById("enddate")).val()
                },
                success: function (data) {
                    $("#main-content").html(data);
                    $('#Loading').hide();
                },
                error: function (xhr, status, error) {
                    var errorM = xhr.responseText;
                    errorM = errorM.replace('""', '');
                    alert(errorM);
                    $('#Loading').hide();
                }
            });
        });
  
    $(function () {

            $("#startDate").datepicker({
                altField: "#alternate",
                altFormat: "DD, d MM, yy",
            format: 'dd-mm-yyyy'
            });
        });      

    $(function () {

            $("#endDate").datepicker({
                altField: "#alternate",
                altFormat: "DD, d MM, yy",
            format: 'dd-mm-yyyy'
            });
        });      

    </script>

<div>

    <div class="row">
        <div class="col-lg-12">
            <h2 style="padding-left:15px;">@resShared.mnuTradingMatchQueue</h2>
            <!-- Begin breadcrumb -->
            <ol class="breadcrumb default square rsaquo sm no-border " style="margin:15px;">
                <li><a href="javascript:;" id="Home"><i class="fa fa-home"></i></a></li>
                <li><a href="#">@resShared.mnuTrading</a></li>
                <li class="active"><a href="#" onclick="dummy(0);return false;"> @resShared.mnuTradingMatchQueue </a></li>
            </ol>
            <!-- Begin breadcrumb -->
            <h1 class="page-sub-header"></h1>
        </div>
    </div>


    <div class="table-responsive">
        <table width="100%" class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <tr>
                <td style="text-align:right">
                    <label>Buyer:</label>
                </td>
                <td style="padding-left:10px; width:200px">
                    @Html.TextBoxFor(m => m.Buyer, Model.Buyer, new { @id = "Buyer", @class = "form-control", style = "width:200px;" })
                </td>
            </tr>
            <tr>
                <td style="text-align:right">
                    <label>Seller:</label>
                </td>
                <td style="padding-left:10px; width:200px">
                    @Html.TextBoxFor(m => m.Seller, Model.Seller, new { @id = "Seller", @class = "form-control", style = "width:200px;" })
                </td>
            </tr>
            <tr>
                <td style="text-align:right">
                    <label>@resShared.lblStatus:</label>
                </td>
                <td style="padding-left:10px; width:200px">
                    @Html.DropDownListFor(m => m.SelectedStatus, Model.StatusList, new { @id = "Status", @class = "form-control", style = "width:200px;" })
                </td>
                <td style="padding-left:10px"></td>
            </tr>
            <tr>
                <td style="text-align:right">
                    <label>@resShared.lblPrice:</label>
                </td>
                <td style="padding-left:10px; width:200px">
                    @Html.TextBoxFor(m => m.TheRate, Model.TheRate, new { @id = "TheRate", @class = "form-control", style = "width:200px;" })
                </td>
                <td style="padding-left:10px"></td>
            </tr>
            <tr>
                <td style="text-align:right">
                    <label>@resShared.lblDateFrom:</label>
                </td>
                <td style="padding-left:10px; width:200px">
                    <input type="text" id="startDate">
                </td>

            </tr>
            <tr>
                <td style="text-align:right">
                    <label> @resShared.lblTo:</label>
                </td>
                <td style="padding-left:10px; width:200px">
                    <input type="text" id="endDate">
                </td>
                <td style="padding-left:10px">
                    <button id="btnsearch" type="button" class="btn btn-sm btn-success" style="width:100px">@resShared.btnSearch</button>
                </td>
            </tr>
            <tr>
                <td style="text-align:right"></td>
                <td style="padding:10px 10px;">
                    <a href="@Url.Action("ExportMatchQueue", "AdminShare", new {Buyer = @Model.Buyer,Seller= @Model.Seller, Status = @Model.SelectedStatus, startdate = @Model.startDate, enddate = @Model.endDate })" class="btn btn-sm btn-primary" target="_blank" style="width:100px">@resShared.btnExport</a>
                </td>
                <td style="padding-left:10px"></td>
            </tr>
        </table>
    </div>
    <div class="table-responsive">
        <table id="tablestyle" border="1" class="table-style table table-th-block table-hover">
            <thead>
                <tr>
                    <th style="text-align: center;color:White">
                        @resShared.lblBuyerAccount
                    </th>
                    <th style="text-align: center;color:White">
                        @resShared.lblSellerAccount
                    </th>
                    <th style="text-align: center;color:White">
                        @resShared.lblVolume
                    </th>
                    <th style="text-align: center;color:White">
                        @resShared.lblAmount
                    </th>
                    <th style="text-align: center;color:White">
                        @resShared.lblLocalAmount
                    </th>
                    <th style="text-align: center;color:White">
                        @resShared.lblStatus
                    </th>
                    <th style="text-align: center;color:White">
                        @resShared.lblDate
                    </th>
                </tr>
            </thead>
            <tbody style="background-color: #eee;">
                @if (Model.TradingSellQueue.Count == 0)
                {
                    <tr style="height: 25px; border-top: 2px solid white;">
                        <td style="padding: 5px;" colspan="10">
                            @resShared.lblNoRecFound
                        </td>
                    </tr>
                }
                @if (Model.TradingSellQueue != null)
                {
                    foreach (var item in Model.TradingSellQueue)
                    {
                        string style = "";

                        <tr style=@style>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Buyer)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Seller)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.OriValue)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Amount)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.LocalAmount)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Status)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.Date)
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    @if (Model.TradingSellQueue.Count > 0)
    {
        <table width="auto" style="text-align:right; margin-right:0px; margin-left:auto;">
            <tr>
                <td style="text-align: right">
                    <div class="BtnClass" style="float: right;">
                        @Html.DropDownList("page", @Model.Pages, new { @class = "form-control", style = "width:80px;" })

                    </div>
                </td>
                <td style="text-align: right">
                    <button id="btnPage" type="button" class="btn btn-sm btn-success" style="width: 100px">@resShared.btnView</button>
                </td>
            </tr>
        </table>
    }
    <br />
    <br />
    <br />

</div>