UnionChain/Controllers/Admin/AdminBonusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using ECFBase.Components;
using ECFBase.Helpers;
using ECFBase.Models;
using System.Text;
using System.IO;
using System.Globalization;

namespace ECFBase.Controllers.Admin
{
    public class AdminBonusController : Controller
    {

        #region Reports

        public ActionResult DailySalesSummary(int selectedPage = 1, int selectedYear = -1, int selectedMonth = -1, int Country = 0)
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("AdminLogin", "Admin", new { reloadPage = true });
            }

            int ok;
            string msg;
            int pages;

            if (selectedYear == -1)
                selectedYear = DateTime.Now.Year;
            if (selectedMonth == -1)
                selectedMonth = DateTime.Now.Month;

            var model = new PaginationCurrentSalesModel();

            #region Country
            //combobox for country

            List<CountrySetupModel> countries = Misc.GetAllCountryID("en-US");

            model.Countries = from c in countries
                              select new SelectListItem
                              {
                                  Text = c.CountryName,
                                  Value = c.CountryCode
                              };

            model.SelectedCountry = Convert.ToString(Country);
            #endregion

            var dsCurrentSales = BonusSettingDB.GetCurrentSales(selectedPage, selectedYear, selectedMonth, Country, out pages, out ok, out msg);
            selectedPage = ConstructPageList(selectedPage, pages, model);

            float TotalTradeableAmount = 0;
            float TotalUntradeableAmount = 0;
            float TotalTopUp = 0;
            float TotalHashBonus = 0;
            float TotalHashPowerBonus = 0;
            float TotalHashPerformanceBonus = 0;
            float LevelBonusAmount = 0;

            //tradeable
            foreach (DataRow dr in dsCurrentSales.Tables[0].Rows)
            {
                var csm = new CurrentSalesModel();
                csm.SalesDate = dr["SalesDate"].ToString();
                csm.NewRegSalesAmount = float.Parse(dr["SalesAmount"].ToString());
                csm.TotalTradeAmount += float.Parse(dr["SalesAmount"].ToString());
                //csm.TotalSalesInBVAmount += float.Parse(dr["SalesInBV"].ToString());
                csm.TotalSalesAmount += float.Parse(dr["SalesAmount"].ToString());
                model.CurrentSalesModel.Add(csm);

                TotalTradeableAmount = TotalTradeableAmount + float.Parse(dr["SalesAmount"].ToString());
            }

            //untradeable
            foreach (DataRow dr in dsCurrentSales.Tables[1].Rows)
            {
                //already has that date
                int nIndex = model.CurrentSalesModel.FindIndex(f => f.SalesDate == dr["SalesDate"].ToString());

                if (nIndex >= 0)
                {
                    model.CurrentSalesModel[nIndex].TotalUntradeAmount = float.Parse(dr["SalesAmount"].ToString());
                    model.CurrentSalesModel[nIndex].TotalSalesAmount += float.Parse(dr["SalesAmount"].ToString());
                    TotalUntradeableAmount = TotalUntradeableAmount + float.Parse(dr["SalesAmount"].ToString());
                }
                else
                {
                    var csm = new CurrentSalesModel();
                    csm.SalesDate = dr["SalesDate"].ToString();
                    csm.TotalUntradeAmount = float.Parse(dr["SalesAmount"].ToString());
                    csm.TotalSalesAmount += float.Parse(dr["SalesAmount"].ToString());
                    model.CurrentSalesModel.Add(csm);

                    TotalUntradeableAmount = TotalUntradeableAmount + float.Parse(dr["SalesAmount"].ToString());
                }
            }

            //Hash
            foreach (DataRow dr in dsCurrentSales.Tables[2].Rows)
            {
                //already has that date
                int nIndex = model.CurrentSalesModel.FindIndex(f => f.SalesDate == dr["SalesDate"].ToString());

                if (nIndex >= 0)
                {
                    model.CurrentSalesModel[nIndex].Hash = float.Parse(dr["SalesAmount"].ToString());
                    TotalHashBonus = TotalHashBonus + float.Parse(dr["SalesAmount"].ToString());
                    model.CurrentSalesModel[nIndex].TotalBonus += float.Parse(dr["SalesAmount"].ToString());
                }
                else
                {
                    var csm = new CurrentSalesModel();
                    csm.SalesDate = dr["SalesDate"].ToString();
                    csm.Hash = float.Parse(dr["SalesAmount"].ToString());
                    csm.TotalBonus = csm.TotalBonus + float.Parse(dr["SalesAmount"].ToString());
                    model.CurrentSalesModel.Add(csm);

                    TotalHashBonus = TotalHashBonus + float.Parse(dr["SalesAmount"].ToString());
                }
            }

            //Hash Power
            foreach (DataRow dr in dsCurrentSales.Tables[3].Rows)
            {
                //already has that date
                int nIndex = model.CurrentSalesModel.FindIndex(f => f.SalesDate == dr["SalesDate"].ToString());

                if (nIndex >= 0)
                {
                    model.CurrentSalesModel[nIndex].HashPower = float.Parse(dr["SalesAmount"].ToString());
                    model.CurrentSalesModel[nIndex].TotalBonus += float.Parse(dr["SalesAmount"].ToString());
                    TotalHashPowerBonus = TotalHashPowerBonus + float.Parse(dr["SalesAmount"].ToString());
                }
                else
                {
                    var csm = new CurrentSalesModel();
                    csm.SalesDate = dr["SalesDate"].ToString();
                    csm.HashPower = float.Parse(dr["SalesAmount"].ToString());
                    csm.TotalBonus = csm.TotalBonus + float.Parse(dr["SalesAmount"].ToString());
                    model.CurrentSalesModel.Add(csm);

                    TotalHashPowerBonus = TotalHashPowerBonus + float.Parse(dr["SalesAmount"].ToString());
                }
            }

            //Performance Hash
            foreach (DataRow dr in dsCurrentSales.Tables[4].Rows)
            {
                //already has that date
                int nIndex = model.CurrentSalesModel.FindIndex(f => f.SalesDate == dr["SalesDate"].ToString());

                if (nIndex >= 0)
                {
                    model.CurrentSalesModel[nIndex].HashPerformance = float.Parse(dr["SalesAmount"].ToString());
                    model.CurrentSalesModel[nIndex].TotalBonus += float.Parse(dr["SalesAmount"].ToString());
                    TotalHashPerformanceBonus = TotalHashPerformanceBonus + float.Parse(dr["SalesAmount"].ToString());
                }
                else
                {
                    var csm = new CurrentSalesModel();
                    csm.SalesDate = dr["SalesDate"].ToString();
                    csm.HashPerformance = float.Parse(dr["SalesAmount"].ToString());
                    csm.TotalReferralAmount = float.Parse(dr["SalesAmount"].ToString());
                    csm.TotalBonus = csm.TotalBonus + float.Parse(dr["SalesAmount"].ToString());
                    model.CurrentSalesModel.Add(csm);

                    TotalHashPerformanceBonus = TotalHashPerformanceBonus + float.Parse(dr["SalesAmount"].ToString());
                }
            }

            //TopUp
            foreach (DataRow dr in dsCurrentSales.Tables[5].Rows)
            {
                //already has that date
                int nIndex = model.CurrentSalesModel.FindIndex(f => f.SalesDate == dr["SalesDate"].ToString());

                if (nIndex >= 0)
                {
                    model.CurrentSalesModel[nIndex].TotalTopUP = float.Parse(dr["SalesAmount"].ToString());
                    model.CurrentSalesModel[nIndex].TotalSalesAmount += float.Parse(dr["SalesAmount"].ToString());
                    TotalTopUp = TotalTopUp + float.Parse(dr["SalesAmount"].ToString());
                }
                else
                {
                    var csm = new CurrentSalesModel();
                    csm.SalesDate = dr["SalesDate"].ToString();
                    csm.TotalTopUP = float.Parse(dr["SalesAmount"].ToString());
                    csm.TotalSalesAmount += float.Parse(dr["SalesAmount"].ToString());
                    model.CurrentSalesModel.Add(csm);

                    TotalTopUp = TotalTopUp + float.Parse(dr["SalesAmount"].ToString());
                }
            }

            //sort first before add total
            var sort = new sortOnSalesDate();
            model.CurrentSalesModel.Sort(sort);

            var totalCSM = new CurrentSalesModel();
            totalCSM.SalesDate = Resources.Admin.lblTotal;
            totalCSM.TotalTradeAmount = TotalTradeableAmount;
            totalCSM.TotalUntradeAmount = TotalUntradeableAmount;
            totalCSM.TotalTopUP = TotalTopUp;
            totalCSM.TotalSalesAmount = TotalTradeableAmount + TotalUntradeableAmount;
            totalCSM.Hash = TotalHashBonus;
            totalCSM.HashPower = TotalHashPowerBonus;
            totalCSM.HashPerformance = TotalHashPerformanceBonus;
            totalCSM.LevelBonusAmount = LevelBonusAmount;
            totalCSM.TotalBonus = TotalHashBonus + TotalHashPowerBonus + TotalHashPerformanceBonus;

            model.CurrentSalesModel.Add(totalCSM);

            ViewBag.selectedYear = selectedYear;
            ViewBag.selectedMonth = selectedMonth;

            return PartialView("DailySalesSummary", model);
        }

        public ActionResult HashBonusList(int selectedPage = 1, int selectedYear = -1, int selectedMonth = -1, int Country = 0, string username ="")
        {

UnionChain/Views/AdminBonus/DirectSponsorSummary.cshtml
@using resShared = ECFBase.Resources.Member;
@using ECFBase.Models
@model DirectSponsorModel
<script type="text/javascript">


    $("#btnPage").click(function (evt) {
        $('#Loading').show();

        var e = document.getElementById("page");
        var page;
        if (e.selectedIndex == -1)
            page = 1;
        else
            page = e.options[e.selectedIndex].value;

        $.ajax({
            type: "POST",
            url: "/AdminBonus/GetTotalDirectSponsor",
            data: { selectedPage: page},
            success: function (data) {
                $("#main-content").html(data);
                $('#Loading').hide();
                event.stopPropagation();
            },
            error: function (xhr, status, error) {
                var errorM = xhr.responseText;
                errorM = errorM.replace('""', '');
                alert(errorM);
                $('#Loading').hide();
            }
        });
    });

    $("#btnSearchByName").click(function (evt) {

        $('#Loading').show();
        $.ajax({
            type: "POST",
            url: "/AdminBonus/GetTotalDirectSponsor",
            data: { username: $('#searchName').val() },
            success: function (data) {
                $("#main-content").html(data);
                $('#Loading').hide();
            },
            error: function (xhr, status, error) {
                var errorM = xhr.responseText;
                errorM = errorM.replace('""', '');
                alert(errorM);
                $('#Loading').hide();
            }
        });

    });


</script>
<div id="reportAd" class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h2 style="padding-left:10px;">@resShared.lblTotalDirectSponsor</h2>
            <!-- Begin breadcrumb -->
            <ol class="breadcrumb default square rsaquo sm no-border " style="margin:10px;">
                <li><a href="javascript:;" id="Home"><i class="fa fa-home"></i></a></li>
                <li><a href="#">@resShared.lblReports</a></li>
                <li class="active"><a href="#" onclick="dummy(0);return false;">@resShared.lblTotalDirectSponsor</a></li>
            </ol>
            <!-- End breadcrumb -->
            <h1 class="page-sub-header">
                <input type="hidden" id="eliminateId" />
            </h1>
        </div>
    </div>

    <div class="col-xs-12" style="padding-bottom:10px; padding-left:0">
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3" style="text-align:right">
            @resShared.lblUsername:
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <input type="text" id="searchName" class="form-control" @*style="width:200px;"*@ />
        </div>
        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5">
            <input id="btnSearchByName" class="btn btn-success" value="@resShared.btnSearch" style="min-width:100px" />
        </div>
    </div>
    <br />
    <table id="tablestyle" width="100%" border="1" class="table-style table table-th-block table-hover" style="padding-left:10px;">
        <thead>
            <tr style="height: 25px;">
                <td align="center"><p style="color:White; text-align:center">@resShared.lblUsername</p></td>
                <td align="center"><p style="color:White; text-align:center">@resShared.lblFullname</p></td>
                <td align="center"><p style="color:White; text-align:center">@resShared.lblTotalDirectSponsor</p></td>
            </tr>
        </thead>
        <tbody style="background-color: #eee;">
            @{

                foreach (var item in Model.TotalSponsorModel)
                {
                    <tr>
                        <td align="center">
                            <div class="divMember" id="@item.MemberID">@item.MemberID</div>

                        </td>
                        <td align="center">
                            <div class="divMember" id="@item.Fullname">@item.Fullname</div>
                        </td>
                        <td align="center">
                            <div class="divMember" id="@item.TotalDirectSponsor">@item.TotalDirectSponsor</div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
@if (Model.Pages.Count() != 0)
{
    <table width="auto" style="text-align:right; margin-right:0px; margin-left:auto;">
        <tr>
            <td style="text-align: right">
                <div class="BtnClass" style="float: right;">
                    @Html.DropDownList("page", @Model.Pages, new { @class = "form-control", style = "width:80px;" })
                </div>
            </td>
            <td style="text-align: right">
                <button id="btnPage" type="button" class="btn btn-sm btn-success" style="width: 100px">@resShared.btnView</button>
            </td>
        </tr>
    </table>
}      

UnionChain/Views/AdminBonus/HashBonusSummary.cshtml
@using ECFBase.Models;
@using resShared  = ECFBase.Resources.Member;
@model PaginationCurrentSalesModel
<script type="text/javascript">
    $("#btnPage2").click(function (evt) {
        $("#btnPage").click();
    });

    $("#btnPage").click(function (evt) {
        $('#Loading').show();

        var e = document.getElementById("page");
        var page;
        if (e.selectedIndex == -1)
            page = 1;
        else
            page = e.options[e.selectedIndex].value;

        var y = document.getElementById("ddlyear");
        var year = y.options[y.selectedIndex].value;

        var m = document.getElementById("ddlmonth");
        var month = m.options[m.selectedIndex].value;

        var C = document.getElementById("SelectedCountry");
        var country = C.options[C.selectedIndex].value;
        
        $.ajax({
            type: "POST",
            url: "/AdminBonus/HashBonusList",
            data: { selectedPage: page, selectedYear: year, selectedMonth: month, Country: country },
            success: function (data) {
                $("#main-content").html(data);
                $('#Loading').hide();
                event.stopPropagation();
            },
            error: function (xhr, status, error) {
                var errorM = xhr.responseText;
                errorM = errorM.replace('""', '');
                alert(errorM);
                $('#Loading').hide();
            }
        });
    });


    $("#btnSearch").click(function (evt) {
        $('#Loading').show();
        $.ajax({
            type: "POST",
            url: "/AdminBonus/HashBonusList",
            data: { username: $('#searchFC').val() },
            success: function (data) {
                $("#main-content").html(data);
                $('#Loading').hide();
                event.stopPropagation();
            },
            error: function (xhr, status, error) {
                var errorM = xhr.responseText;
                errorM = errorM.replace('""', '');
                alert(errorM);
                $('#Loading').hide();
            }
        });
    });

</script>
<div class="row">
    <div class="col-lg-12">
         <h2 style="padding-left:10px;">@resShared.mnuHashBonusSummary</h2>
    <!-- Begin breadcrumb -->
				<ol class="breadcrumb default square rsaquo sm no-border " style="margin:10px;">
					<li><a href="javascript:;" id="Home"><i class="fa fa-home"></i></a></li>
					<li><a href="#">@resShared.lblReports</a></li>
					<li class="active"><a href="#">@resShared.mnuHashBonusSummary</a></li>
				</ol>
		<!-- End breadcrumb -->
        <h1 class="page-sub-header">
        </h1>
    </div>
</div>
<div>
    <div class="grid" style="margin-left: 5px;" id="grid">
        <div class="grid">
            <div>
                <table width="100%" class="test">
                    <tr>
                        <td style="text-align: right">
                            <strong>@resShared.lblCountry</strong>
                        </td>
                        <td style="padding-left: 10px; width: 100px">
                            @Html.DropDownListFor(m => m.SelectedCountry, @Model.Countries, new { @id = "SelectedCountry", @class = "form-control" })
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right">
                            <label>@resShared.lblYear:</label>
                        </td>
                        <td style="padding-left: 10px; width: 100px">
                            @Html.DropDownList("ddlyear", new SelectList(new List<Object>{
                                                                                         new {value = DateTime.Now.Year , text = DateTime.Now.Year},
                                                                                         new {value = DateTime.Now.Year - 1 , text = DateTime.Now.Year - 1 }}, "value", "text", @ViewBag.selectedYear), new { @class = "form-control", style = "width:200px;" })

                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: right">
                            <label>@resShared.lblMonth:</label>
                        </td>
                        <td style="padding-left: 10px; width: 100px">
                            @Html.DropDownList("ddlmonth", new SelectList(new List<Object>{
                                                                                          new {value = 1 , text = "January"},
                                                                                          new {value = 2 , text = "February" },
                                                                                          new {value = 3 , text = "March" },
                                                                                          new {value = 4 , text = "April" },
                                                                                          new {value = 5 , text = "May" },
                                                                                          new {value = 6 , text = "June" },
                                                                                          new {value = 7 , text = "July" },
                                                                                          new {value = 8 , text = "August" },
                                                                                          new {value = 9 , text = "September" },
                                                                                          new {value = 10 , text = "October" },
                                                                                          new {value = 11 , text = "November" },
                                                                                          new {value = 12 , text = "December" }}, "value", "text", @ViewBag.selectedMonth), new { @class = "form-control", style = "width:200px;" })
                        <td style="padding-left: 10px; width: 200px">
                            <button id="btnPage2" type="button" class="btn btn-sm btn-success" style="width: 100px">@resShared.btnView</button>
                        </td>
                        <td style="padding-left: 50px"></td>

                    </tr>
                    <tr>
                        <td style="text-align: right">
                            <label>@resShared.lblUsername:</label>
                        </td>
                        <td style="padding-left: 10px; width: 100px">
                            @*<input type="text" class="form-control" id="searchFC" />*@
                            @Html.TextBoxFor(m => m.MemberID, Model.MemberID, new { @id = "searchFC", @class = "form-control", style = "width:200px;" })
                        </td>
                        <td style="padding-left: 10px; width: 200px">
                            <button id="btnSearch" type="button" class="btn btn-sm btn-success" style="width: 100px">@resShared.btnSearch</button>
                        </td>

                    </tr>
                    <tr>
                        <td style="text-align:right"></td>
                        <td style="padding:10px 10px;">
                            <a href="@Url.Action("ExportHashBonus", "AdminBonus", new {type ="Hash", username = @Model.MemberID, selectedYear = @ViewBag.selectedYear, selectedMonth = @ViewBag.selectedMonth, Country = @Model.SelectedCountry})" class="btn btn-sm btn-primary" target="_blank" style="width:100px">@resShared.btnExport</a>
                        </td>
                        <td style="padding-left:10px"></td>
                    </tr>
                </table>
            </div>
            <br />
            <div class="table-responsive">
                <table id="tablestyle" class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr style="background-color: #414558;">
                            <th style="text-align: center;color:White">
                                @resShared.lblDate
                            </th>
                            <th style="text-align: center;color:White">
                                @resShared.lblUsername
                            </th>
                            <th style="text-align: center;color:White">
                                @resShared.lblAmount
                            </th>
                            <th style="text-align: center;color:White">
                                @resShared.lblRemark
                            </th>
                            <th style="text-align: center;color:White">
                                @resShared.lblExtraInfo
                            </th>                           

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.HashBonusModel)
                        {
                            <tr>
                                <td align="center">
                                    @Html.DisplayFor(modelItem => item.SalesDate)
                                </td>
                                <td align="center">
                                    @Html.DisplayFor(modelItem => item.MemberID)
                                </td>
                                <td align="center">
                                    @string.Format("{0:n2}", item.SalesAmount)
                                </td>
                                <td align="center">
                                    @Html.DisplayFor(modelItem => item.CashName)
                                </td>
                                <td align="center">
                                    @Html.DisplayFor(modelItem => item.Remarks)
                                </td>

                            </tr>

                        }
                        @if (ViewBag.TotalAmount != null)
                        {

                            <tr>
                                <td align="center"></td>
                                <td align="center">
                                    @resShared.lblTotalAmount
                                </td>
                                <td align="center">
                                    @string.Format("{0:n2}", ViewBag.TotalAmount)
                                </td>
                                <td align="center"></td>
                                <td align="center"></td>

                            </tr>

                        }
                    </tbody>
                </table>
            </div>
            @if(Model.Pages.Count() != 0)
            { 
            <table width="auto" style="text-align:right; margin-right:0px; margin-left:auto;">
                <tr>
                    <td style="text-align: right">
                        <div class="BtnClass" style="float: right;">
                            @Html.DropDownList("page", @Model.Pages, new { @class = "form-control", style = "width:80px;" })                    
                        </div>
                    </td>
                    <td style="text-align: right">
                            <button id="btnPage" type="button" class="btn btn-sm btn-success" style="width: 100px">@resShared.btnView</button>
                    </td>
                </tr>
            </table>
            }
        </div>
    </div>
</div>
        